<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.JellyMetaLocal</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.JellyMetaLocal</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <DefaultItemExcludes>$(DefaultItemExcludes);tests\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.11" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.11" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\PluginConfigurationPage.html" />
    <EmbeddedResource Include="logo.png" />
  </ItemGroup>

</Project>
